### ISSUE TITLE
Reminders about open PRs

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#101]
When a PR in my project is open for longer than `n` time units, Zappr should send a reminder email to a configured email address. If no action is taken by the receiver(s), Zappr should close the PR after `m` time units. An example for such action could be a button in the email "keep PR open".

**Comment by whiskeysierra** [comment]
> When a PR in my project is open for longer than n time units, Zappr should send a reminder email to a configured email address.

👍 

> If no action is taken by the receiver(s), Zappr should close the PR after m time units. An example for such action could be a button in the email "keep PR open".

😐

**Comment by prayerslayer** [comment]
Why "meh" about the second part? Is it because of autoclose or emails?

**Comment by whiskeysierra** [comment]
Auto-close. I think closing a pull request should not be taken lightly. Somebody offered support, the least we can do is give some comment why we rejected it.

**Comment by prayerslayer** [comment]
Yeah I understand. I think it depends on the time frame and PR activity. If there's a PR open (and stale, ie no discussion or commits) for 6 months it doesn't really matter anymore if you write a police message or not.

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
