### ISSUE TITLE
Proper issue templates

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#103]
- Ability to put templates (mustache?) in a .zappr folder in the project
- New issues are checked against templates and labeled accordingly
- Option to autoclose issues that do not match any template
- Figure out what to do with info that can be extracted from templates, like version numbers, most common words in stack trace…

**Comment by whiskeysierra** [comment]
A less strict approach would be to use [Github's own Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
