### ISSUE TITLE
Label state machine

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#104]
Figure out a way for people to define state transitions for issues via labels. The main obstacle here is the feedback loop: One adds a label, representing an invalid transition, and then what? Just remove it again? If so, how to inform user about invalid transition? Email?

**Comment by Raffo** [comment]
I was about to add an issue, we would love to have labels as checks before merge, like having WIP or READY_FOR_MERGE... is this issue part of it somehow? Do you also accept contributors?

**Comment by botchniaque** [comment]
+1 - we I would also love to have at least not mergable `WIP`s

**Comment by prayerslayer** [comment]
@Raffo Not really, this was meant to be a JIRA-like workflow where you have labels for each ticket state (like `spec`, `in_progess`, `in_review` etc) and can somehow model which state transitions are valid.

I'll open a new ticket for what you are proposing.

**Comment by prayerslayer** [comment]
Closing in favor of #323
