### ISSUE TITLE
STUPS integration

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#105]
* Create review approvals in Kio automatically after they were given in Zappr.

**Comment by hjacobs** [comment]
What is this ticket about?

**Comment by prayerslayer** [comment]
@hjacobs: As a first step to create review approvals in Kio automatically after they were given in Zappr. This came up as an idea in our first slingshot sprint.

**Comment by elgalu** [comment]
This feature would be so handy however the difficulty I see here is that Zappr will have to somehow impersonate the approver Kio credentials so the approval is kept under his/her name.

**Comment by prayerslayer** [comment]
Closing because there are no immediate plans to do this.
