### ISSUE TITLE
Ticket reference checks

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#106]
Main obstacle: Tickets that do not live in same Github installation. Not the common case, but might happen.

**Comment by prayerslayer** [comment]
Possible solution: Just verify that the commit message looks like there's a ticket referenced (ie regex again), not actually checking it's a valid, existing ticket.

**Comment by lukasniemeier-zalando** [comment]
:+1: let me configure a RegEx verifying the branch Name and each commit MSG on a PR

**Comment by jmcs** [comment]
If you need the regexes I have them for [Jira tickets](https://github.com/zalando/turnstile/blob/11e213b9d32d5fd93783ebef5107c0b21ab6e3c4/turnstile/models/specifications.py#L123) and [Github issues](https://github.com/zalando/turnstile/blob/11e213b9d32d5fd93783ebef5107c0b21ab6e3c4/turnstile/common/github.py#L9) in turnstile.

**Comment by prayerslayer** [comment]
@jmcs Thanks. I guess we will just leave the regexes up to our (opensource) users, but for the GHE version of Zappr it definitely makes sense to have them as default.
