### ISSUE TITLE
Approvals for releases and deployments

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#126]
Some people I've talked to say that approving releases and/or deployments is very important to them. How could we address this?

**What we need to understand**
* how do teams prepare a release?
* how do teams deploy a release?
* which steps should be automated and which need to be manual?

**Notes**
* probably related to #105
* could use [Github deployment API](https://developer.github.com/v3/repos/deployments/)

**Comment by elgalu** [comment]
This makes me worry which is the right place to do this, let's analyze some workflows:

1. User writes **deploy** in a PR comment

2. Zappr server process this *deploy* comment and POST to Github depl endpoint.

Reading the docs we see:

> GitHub then dispatches deployment events that external services can listen for and act on.

In this sentence, *external services* would likely be our CD tool, namely Jenkins/GoCD/Travis/... 

My question would be, why not directly send the event from Zappr to our CD tool?

But if *external services* is still Zappr then this feature makes more sense and so does #105 however that implies adding CD features into Zappr, namely deploy commands reports (Jenkins: console outpus), deploy job scheduling (Jenkins: executors), deployment access control, i.e. application write all scopes and so on...

**Comment by prayerslayer** [comment]
Closing as I feel this is out of scope for Zappr.
