### ISSUE TITLE
Show zappr status as "In progress" when having too few approvals

### ISSUE THREAD

**Issue by harti2006** [zalando/zappr#146]
Is it possible to mark a pull request, that has not yet received enough approvals, as "In progress" (yellow dot) instead of "Failed"? It always looks like something really went wrong, when I see that red cross on my commits / pull requests.

**Comment by prayerslayer** [comment]
We had this discussion also and decided to use the failed status as Zappr is technically not processing your pull request when there is an approval missing. We try to leverage existing knowledge from developers about Travis (see also: `.zappr.yml`), so it seemed like a good idea to use yellow for "we're processing this" and red for "we're done and our check failed".

I can understand your sentiment though. Not sure what to do.

**Comment by mfellner** [comment]
I would personally prefer the "pending" status too.

Plus, I could imagine a scenario where we use the "failed" status for a rejected pull request or something else more severe. Maybe we could also make it user-configurable in .zappr.yml?

**Comment by prayerslayer** [comment]
Ya another config option sounds ok to me.

**Comment by hjacobs** [comment]
:+1:

**Comment by mrandi** [comment]
👍

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by Excds** [comment]
:+1: I totally agree that the pending state would be much better than failed.
