### ISSUE TITLE
Consider using the recommended .yaml extension for YAML files

### ISSUE THREAD

**Issue by hjacobs** [zalando/zappr#148]
http://www.yaml.org/faq.html suggests using `.yaml` were possible:

> Is there an official extension for YAML files?
>
> Please use ".yaml" when possible.

We are usually using `.yaml` in Zalando, e.g. in all STUPS tool and e.g. https://github.com/zalando/zmon/blob/master/.catwatch.yaml .

I think the "8.3" times are over long ago :smirk: 

We are also not using `.jsn` instead of `.json` :speak_no_evil: ..

**Comment by prayerslayer** [comment]
We settled for only `.yml` because Travis does so too, but I agree it's inconvenient and can be confusing too, so we should allow both.

**Comment by hjacobs** [comment]
@prayerslayer just checked the Travis source code, it has `.travis.yml` hardcoded. I upvoted the closed issue https://github.com/travis-ci/travis-ci/issues/672 :smirk:

**Comment by hjacobs** [comment]
@prayerslayer is `.yaml` already supported for us (i.e. is it deployed?)?

**Comment by prayerslayer** [comment]
Not yet deployed.

**Comment by hjacobs** [comment]
@prayerslayer we should also rename/move the example files and in the docs :smile:
