### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#211]
I think we're quite good with tests, but it's a shame that there's no badge showing _how_ good.

**Comment by lotharschulz** [comment]
what about badges like codecov.io? 
https://github.com/lotharschulz/spray-playground/blob/master/README.md shows how this can look like (and if you have low coverage)

**Comment by prayerslayer** [comment]
Sure, but we have to set up [istanbul](https://gotwarlost.github.io/istanbul/) or something similar to measure the coverage in the first place 😃

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
