### ISSUE TITLE
Encryption of tokens

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#22]
Maybe with KMS so we don't have to take care of the encryption key.

- [x] A token is saved inside each check (#25)
- [x] Tokens are handled by the NullEncryptionService for development
- [ ] Tokens hare handled by the KmsEncryptionService in production

**Comment by mfellner** [comment]
The encryption can be done inside a [hook](http://docs.sequelizejs.com/en/latest/docs/hooks/#instance-hooks).
