### ISSUE TITLE
Beautify ReadTheDocs with Zappr logo

### ISSUE THREAD

**Issue by hjacobs** [zalando/zappr#226]
Add Zappr logo (in RTD sidebar), because everybody loves pretty docs :smile: 

https://zappr.readthedocs.org/

**Comment by prayerslayer** [comment]
Along the way we should change the URL to `readthedocs.io`.

**Comment by PeterZalando** [comment]
Which icon do you mean? The one with the text or just the mascot?
See below a preview showing both so you can compare.

I like the one with the text more. (and it already has transparent background…)

![image](https://cloud.githubusercontent.com/assets/25012935/23573180/7249992a-0074-11e7-8d1a-75a9d4721d65.png)

**Comment by PeterZalando** [comment]
for the mentioned commit I went with the logo including the "zappr" text in the vertical navigation menu

**Comment by hjacobs** [comment]
Looks good on https://zappr.readthedocs.io/en/latest/ --- closing :smile:
