### ISSUE TITLE
Configure Sentry using raven.js

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#228]
The nice folks at [getsentry.com](https://getsentry.com) are sponsoring an account for us.  Let's integrate it!
- [ ] frontend exceptions (React)
- [x] global backend exceptions (Koa)
- [ ] backend request errors ([error middleware](https://github.com/koajs/error))

**Comment by LappleApple** [comment]
@mfellner @prayerslayer Hey guys, is this still in progress?
