### ISSUE TITLE
Mandatory approvers

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#239]
We could check for mandatory approvery by looking for `<keyword>: <mentions>` in comments from the PR author.

**Comment by jmcs** [comment]
\<bike-shedding>The keyword could be `Reviewers:`\</bike-shedding>

**Comment by hjacobs** [comment]
I would propose (as a default) to have something like a natural language:

> {list-of-mentions} please review.

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
