### ISSUE TITLE
Custom configuration is ignored

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/zappr#247]
Seems like the custom configuration file `.zappr.yml` is ignored and a default configuration is used on my repository.

	approvals:
	  minimum: 2
	  pattern: "^(:sunny:|☀)$"
	  from:
	    collaborators: true
	commit:
	  message:
	    patterns:
	      - "^[A-Z]+-[0-9]+.*"
	autobranch:
	  pattern: "{number}-{title}"
	  length: 60

Despite this configuration zappr detects :+1: as approvals and rejects a git message like "PROJECT-2". Since my repository is on GHE I cannot link to it :cry:. Any way for me to debug this?

**Comment by lukasniemeier-zalando** [comment]
Seems like after a while (~10min?) the configuration was synced. Now zappr works with my custom config :+1:

**Comment by prayerslayer** [comment]
Hmmmm there should be no "syncing" involved as Zappr gets the config file from your repo (master branch) on every call.

**Comment by whiskeysierra** [comment]
I have the same issue, but it won't update. See zalando/problem-spring-web#35, it says I'm missing 2 approvals but my config in the master branch says a minimum of 1 is required.

**Comment by prayerslayer** [comment]
I have this seen before — a seemingly correct zapprfile is in the repo, but zappr falls back to default configuration. So either it can read the file and for some reason ignores it (parsing error?) or it can't read it in the first place. We will look into this.

**Comment by prayerslayer** [comment]
@whiskeysierra Apparently in your case this is a YAML parse error. The zapprfile of zalando/problem-spring-web contains `pattern: "\+1"`, but should be `pattern: "\\+1"` just as in the [.zappr.yaml example](https://github.com/zalando/zappr/blob/master/.zappr-example.yaml#L5).

**Comment by whiskeysierra** [comment]
When I'm testing it with regex101.com (as suggested in the docs), it only works with a single slash.

**Comment by hjacobs** [comment]
@whiskeysierra I guess that's because YAML adds another layer of backslash escapes:

```python
>>> yaml.safe_load(r'x: "\\+"')
{'x': '\\+'}
>>> yaml.safe_load(r'x: "\+"')
Traceback (most recent call last):
found unknown escape character '+'
  in "<string>", line 1, column 6:
    x: "\+"

**Comment by whiskeysierra** [comment]
Should we add that to the part of the docs? Also, have we thought about how users of Zappr can find out about issues like that (or are issues the way to go here?).

**Comment by prayerslayer** [comment]
We should add this to the docs definitely. And I think the way to inform our users (for now) would be to put an `error` state on the pull request with the error message from `js-yaml`.
