### ISSUE TITLE
Enforce commit message to be formatted uniformly

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/zappr#253]
The commit message check allows you to enforce a specific style of commit messages, e.g. all have to start with "#{issue_number}". Currently the check runs on every commit individually, for example allowing for pull requests with commits referencing several issues.

I want to enforce commit messages to be formatted uniformly, effectively allowing me to enforce that they reference exactly one issue.

**Comment by prayerslayer** [comment]
I can see that this would be useful, but think we can do better with naming :)

Generically speaking what this does putting a limit on the number of different prefixes that match the pattern. Maybe call it `max_prefixes` or something? Not good with names...

**Comment by lukasniemeier-zalando** [comment]
I was also thinking of `prefix` but what if someones wants to have his ticket references at the end?

**Comment by prayerslayer** [comment]
True. ಠ_ಠ

`max_distinct_matches` and requiring a capturing group in the provided pattern?

**Comment by lukasniemeier-zalando** [comment]
This would allow for the use case of allowing "up to `n` referenced tickets" :thought_balloon: 

I tried to go with a capture group but (a) seemed a bit hard to understand especially if users mix regexes with and without captures (e.g. the default do not have capturing groups currently) and (b) code got messy (probably my fault). That's why I went for a group-less solution in #254.

**Comment by prayerslayer** [comment]
Closing this as the discussion didn't lead anywhere. Please reopen if you have fresh ideas :grin:
