### ISSUE TITLE
Enterprise default pattern does not match Jira tickets

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#257]
The [default pattern](https://github.com/zalando/zappr/blob/master/config/app-enterprise.yaml#L14) does not match branch names with Jira tickets, e.g. `BS-1234 I am a ticket`.

**Comment by prayerslayer** [comment]
Which branches?

And the ticket you are describing should be matched by the pattern on the next line? https://github.com/zalando/zappr/blob/master/config/app-enterprise.yaml#L15

**Comment by mfellner** [comment]
Could not reproduce.
