### ISSUE TITLE
Org membership is ignored (need collaborators: true)

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#258]
In one repository (https://github.bus.zalan.do/codebrewers/cms-app-service) without explicit collaborators setting only the organisation and `collaborators: false` causes an approval to be ignored (fall through to [Approval.js#L83](https://github.com/zalando/zappr/blob/1744e279ecd7dfec8c5ec378d2c866f4006bc640/server/checks/Approval.js#L83).

But when setting `collaborators: true`, the approver is identified as a collaborator (exit at [Approval.js#L70](https://github.com/zalando/zappr/blob/1744e279ecd7dfec8c5ec378d2c866f4006bc640/server/checks/Approval.js#L70).

**Comment by prayerslayer** [comment]
Remember that org membership checks only for public members, I can imagine that you find those private members with the `collaborators`.

**Comment by mfellner** [comment]
I debugged the app and can confirm that organization members can in fact approve without setting approvers=true.
