### ISSUE TITLE
Approver groups

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#283]
This is somewhat related to #239. It would be cool if we could define approver groups and require approvals from them.

Suggested configuration syntax:

~~~ yaml
approvals:
  minimum: 2 # overall, counts definitions in `groups` and `from`
  from:
    users:
      # list of external contributors
  groups:
    # group definition is like `approvals`
    zalandos:
      minimum: 2 # approval check fails if < 2 approvals from this group
      orgs:
        - zalando
    backend:
      minimum: 1 # approval check fails if < 1 approvals from this group
      users:
        # list of backend devs
~~~

- [x] Implementation
- [x] Docs

**Comment by mfellner** [comment]
I like this idea. How could be define a group? Two ideas come to my mind:
* groups could be Github teams
* groups could be specified in .zappr.yaml

**Comment by prayerslayer** [comment]
I thought a group definition to basically take the same arguments as you would put into `from` (which also works the same way, ie `OR` concatenation), plus how many you want from that group (`minimum`). And define them in your Zapprfile, because Github teams are unfortunately kind of complicated last time I checked (membership verification only for org owners, only numerical IDs...).

**Comment by mfellner** [comment]
Let's not forget the documentation!

- [ ] Implementation
- [ ] Docs
