### ISSUE TITLE
Change "no self-approval" logic

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#284]
Currently we just ignore the PR opener to prevent people from self-approving pull requests. However it would be better to ignore the last committer instead.

Consider the following case: 

1. Alice commits stuff, opens pull request 1
2. Bob commits stuff on PR 1 too
3. Bob can now legally approve his own changes.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
This allows:

1. Alice commits stuff, opens pull request 1
2. Bob commits stuff on PR 1 too
3. Alice can now legally approve Bob's changes.

Which is IMHO totally fine (Bob implicitly approved/accepted Alice' previous commits by working on her code).

**Comment by whiskeysierra** [comment]
The current behavior (after the change) feels a bit counter-intuitive. We enabled the *Require branches to be up to date before merging* feature for our master branch. If a pull request is out of date Github is nice enough to give us a "Update Branch" button. An update is nothing more than a merge from the target branch into the feature branch. The problem now is, that this merge is made by the one clicking the button. So I can do either click the button and not approve or the other way around, but not both. Was that intended?

**Comment by prayerslayer** [comment]
You can either disable the "require branches to be up to date" option or configure the intended behavior soon (merged, not yet deployed, is on my todo list for today).

> An update is nothing more than a merge from the target branch into the feature branch.

A commit contains a set of changes, we don't really care about who made them. They have to be approved separately.
