### ISSUE TITLE
Allow to veto (prevent a PR from getting merged)

### ISSUE THREAD

**Issue by hjacobs** [zalando/zappr#287]
We should allow developers to do :-1: on PR to prevent getting it merged.

Use case: a senior developer sees that a PR should never (in the current state) get merged, this should not be overruled by other people approving.

**Comment by hjacobs** [comment]
This was proposed by @a1exsh

**Comment by prayerslayer** [comment]
So any 👎 would block forever until the PR is updated?

**Comment by hjacobs** [comment]
@prayerslayer yes, obviously the :-1: comment might also be deleted (e.g. if others convince him that the PR fine...).

**Comment by prayerslayer** [comment]
Sure thing, if a comment is edited/deleted we evaluate the whole situation again anyways.

Yeah, sounds legit to me.

**Comment by spaudanjo** [comment]
instead of deleting the veto/'thumbs down' comment and changing the comments history afterwards, a 'neutralising' of it via an 'thumbs up' comment later on might be interesting (can of course only be done by the same author of the original 'thumbs down' veto)

**Comment by spaudanjo** [comment]
we decided for 'deleting a thumbs down unblocks the pull request again' instead of the described 'neutralising the block via a thumbs up afterwards' approach

**Comment by spaudanjo** [comment]
Suggestion for .zappr.yaml
~~~ yaml 
approvals:
  # PR needs at least 2 approvals
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  # veto/blocking a PR = comment that matches this regex
  veto_pattern: "^(:\\-1:|👎)$"
...

**Comment by hjacobs** [comment]
I guess vetos should only be possible by a certain group of people. How would this look like in `.zappr.yaml`?

**Comment by prayerslayer** [comment]
We planned that everyone who is allowed to approve can also veto. What's the argument against?

**Comment by hjacobs** [comment]
@prayerslayer in general I agree, but often we will see that approvers are a larger group (e.g. all zalando org members) for convenience --- teams might allow vetos only from maintainers to prevent "getting stuck" with some veto.

That said, I think your assumption (group of approvers = group of people who can veto) is fine.

**Comment by spaudanjo** [comment]
Updated suggestion for .zappr.yaml

~~~ yaml
approvals:
  # PR needs at least 2 approvals
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  veto: 
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|👎)$"
...
~~~

**Comment by whiskeysierra** [comment]
👍

**Comment by jmcs** [comment]
@spaudanjo that suggestion looks confusing, approval pattern is a top level configuration but veto is a nested configuration.

**Comment by prayerslayer** [comment]
Yes we had this discussion also. The top level "approval" is supposed to reference the feature itself (think of the toggle in the UI), that's why it would be weird to have "veto" top level. Also you can't have vetos without approvals...

**Comment by spaudanjo** [comment]
#300
