### ISSUE TITLE
Log YAML parse errors

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#295]
Currently zappr sometimes falls back to default configuration for no obvious reason and apparently this is a oftentimes a YAML parse error. We cannot prevent user errors, but this should be logged at the very least. We could also provide the `js-yaml` error message via an `error` commit status instead of silently falling back to default.

**Comment by jmcs** [comment]
You should show it in the UI, maybe by changing the circle on the left side of the repository name and including the details in the repository page.

**Comment by prayerslayer** [comment]
Hm I dunno if that is obvious enough. Maybe there could be a "verify .zappr.yaml" button in the UI.
