### ISSUE TITLE
CircleCI for building Docker images

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#298]
We need a *reliable* infrastructure to build Docker images. Let's try CircleCI.

**Comment by hjacobs** [comment]
@mfellner how will you push to the Open Source Docker Registry (Pier One) from Circle CI?

**Comment by mfellner** [comment]
By building another Docker image that uses the original image as a base ... :trollface: 🚎

**Comment by mfellner** [comment]
I finally managed to get the Jenkins job running: https://zapper.ci.zalan.do/job/npm-build-and-docker-push
Closing this issue for now.
