### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#30]
* ~~modify passport module to support github enterprise~~
* provide the necessary configuration options
* use the original [jaredhanson/passport-github](https://github.com/jaredhanson/passport-github) with Github Enterprise support

**Comment by lukasniemeier-zalando** [comment]
Looking forward to use this plugin, any estimation on GHE support?

**Comment by prayerslayer** [comment]
Q2 / Sprint 1 starts next week and I think it's the first thing we'll tackle. So **iff** all goes really well, end of next week.

**Comment by lukasniemeier-zalando** [comment]
Great to hear - if you need someone for beta testing contact me :phone:

**Comment by lukasniemeier-zalando** [comment]
See.https://github.com/jaredhanson/passport-github/pull/5

**Comment by mfellner** [comment]
Thanks @lukasniemeier-zalando for pointing out that other library. The one we are using, [cfsghost/passport-github](https://github.com/cfsghost/passport-github) (and the only one documented at passportjs.org ...), does not have GHE support. I am going to update the ticket accordingly.
