### ISSUE TITLE
Do not reset approval counter on master merges

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/zappr#310]
Provide a configurable feature to disable approval counter reset by merges from master

**Comment by whiskeysierra** [comment]
> Provide a configurable feature to disable approval counter reset by merges from <del>master</del> **target branch**

**Comment by fragsalat** [comment]
:+1:

**Comment by prayerslayer** [comment]
Sorry for way too late response. I would be okay with this feature if it's only for automatic merge commits done by GitHub (ie when you press "Update branch" button). Commits by humans would still need to be reviewed (as there could have been conflicts that were resolved etc.)

**Comment by whiskeysierra** [comment]
> I would be okay with this feature if it's only for automatic merge commits done by GitHub (ie when you press "Update branch" button)

Can you tell those two types of merges apart?

**Comment by prayerslayer** [comment]
I didn't look too deep in it yet, but think so, yes. It should be possible to make the distinction based on who is the `committer`. But I need to check how easy it is to fake it.

**Comment by whiskeysierra** [comment]
It's the one pressing the button. Looks the same as if he would do that
manually, I'd assume.

**Comment by prayerslayer** [comment]
No, that's the author. The committer is this user: https://github.com/web-flow

**Comment by AlexanderYastrebov** [comment]
AFAIK merge master means thet there is no diff between master and target branch form master point of view:
```
git checkout master
git diff feature/my-target
```

**Comment by AlexanderYastrebov** [comment]
It is the opposite of target branch being not synced with master - the diff is not empty from masters POV

**Comment by prayerslayer** [comment]
@AlexanderYastrebov Sorry, I don't get your point/proposal.

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
