### ISSUE TITLE
Github API: Rate limit exceeded

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#311]
What to do if a user enabled lots of very active repositories?

**Comment by hjacobs** [comment]
The "user" also could have other scripts running which make it very easy to reach GitHub rate limits :smirk:

**Comment by prayerslayer** [comment]
Maybe a user can create a robot user for those other scripts as a first step? Zappr relies on those personal access tokens.

**Comment by prayerslayer** [comment]
The proper solution I think would be to do requests which are not dependent on a user (e.g. fetch commits from a PR and such) with a global, user-independent OAuth token. However in the eyes of Github this is just another token with the same constraints concerning rate limiting, so we would probably run into this problem sooner and for every repository?

**Comment by prayerslayer** [comment]
Closing because I think there is just no good solution to this :sob:

**Comment by prayerslayer** [comment]
Reopening because there is hope with [Integration JWTs](https://developer.github.com/early-access/integrations/authentication/#as-an-integration).

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
