### ISSUE TITLE
Add multiline flag to approval regex

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#314]
Use case: 👍 sent as emails do not count because of multiline comment body. See e.g. https://github.com/zalando-zmon/zmon-docs/pull/29
## Needed
- [ ] Approval check supports approvals with multiple lines, e.g. `:+1:\n\nOriginal message:...`
- [ ] +1 should still be required on first line to avoid ambiguity
- [ ] Tests

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
