### ISSUE TITLE
Add --axe option to cut hands of committer if PR changes more than 10 lines of code.

### ISSUE THREAD

**Issue by pfigue** [zalando/zappr#322]
As someone who has to review Pull Requests,
I want to prevent my mates to send PRs which can't be reviewed but only politely rejected,
so I can merge them after being really sure they are not dangerous and/or they are not polluting the codebase.

For this reason, I'd need an --axe option to prevent too _disruptive_ PRs.

**Comment by hjacobs** [comment]
Sorry, I don't get it :smirk: --- Zappr is not a CLI tool, so where would the `--axe` option be?

**Comment by prayerslayer** [comment]
Hi, I'll close this due to inactivity. Just reopen if you want to explain your issue in more detail.
