### ISSUE TITLE
Allow/deny merge with labels

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#323]
The discussion in #104 requested to allow or deny a merge depending on which labels it has. For instance a PR with the label `WIP` on it should never be mergable. (As a workaround for non-mergable WIPs you can add a veto (:-1:) and remove it when you finished.)

This could look like this:

~~~ yaml
pull_request:
  labels:
    required_for_merge:
      # PR is blocked until it has all of these labels
      - ready_to_merge
    block_merge:
      # PR is blocked as long as it has at least one of these labels
      - WIP
      - in_review 
      - to_be_discussed
~~~

Any objections?

**Comment by yhuard** [comment]
Hi @prayerslayer and thanks for the good work!

The `block_merge` functionality could have been useful for me, why was it removed? Let's say I have a PR with the WIP label, I obviously don't want it to be merged. On the other hand, I don't want to add `ready_to_merge` labels on PRs since it's redundant with the other checks I have (CI tests, approvals, code reviews) and could be confusing as well: what does it mean when the checks are red but the `ready_to_merge` label is present? 

As you mentioned it, there's the 👎 workaround but it's not very elegant. The first solution you suggested was the best.

**Comment by prayerslayer** [comment]
> why was it removed?

Basically we thought that `block-merge` is redundant when you can express "merge only with these labels."

> I don't want to add ready_to_merge labels on PRs since it's redundant with the other checks I have (CI tests, approvals, code reviews)

That's a good consideration you have there. On the other hand one could have the situation where a feature is implemented (say, app can use a database) but whether or not you can merge depends on external factors (like the database actually being available). Then you wouldn't want to merge it despite green status checks. But maybe this is not a common case.

> could be confusing as well: what does it mean when the checks are red but the ready_to_merge label is present?

I would just say it means that someone thought a PR would be finished when automated systems disagree.

**Comment by yhuard** [comment]
Thanks for your reply!

> On the other hand one could have the situation where a feature is implemented (say, app can use a database) but whether or not you can merge depends on external factors (like the database actually being available). Then you wouldn't want to merge it despite green status checks. But maybe this is not a common case.

Then you could also use a blocking label (let's call it `external resource needed`), right? And remove it once the db is ready/available. In the end, it's just a matter of taste but I liked the idea of blocking labels.

**Comment by joefraley** [comment]
Fwiw, it's common to label PRS by feature, bug, hitfix, etc. There is currently no way to allow those standard labels AND block a WIP label.

**Comment by prayerslayer** [comment]
I mean, maybe we made the wrong call there. Do you have suggestions how we would implement this in a backwards-compatible way? Would you care enough to submit a PR afterwards?

**Comment by joefraley** [comment]
I can look into it

**Comment by prayerslayer** [comment]
Cool! Please open a PR with a proposal before you invest a big amount of time.

**Comment by ePaul** [comment]
A use case I just came across was this:

* There must be at least one of the labels X, Y, Z on the PR before merging. (We have several teams working in one repository, and want each PR to have a team label.)
* Other labels might be there in addition.
* If the PR has a "DON'T MERGE" label, it can't be merged.

**Comment by michael-lefkowitz-techlabs** [comment]
Was there any follow up work to add back in the `verboten` / `block_merge` option? My company has a `DoNotSubmit` label that is especially useful when something passes review, but later after rebasing on `master` ends up being broken (in a way not handled by other checks). It would be cool to block the occasional PRs with this label, but would be way too much overhead to require everyone in the company to add a `ReadyToMerge` label to every PR.
