### ISSUE TITLE
Automatically create .zapper.yaml

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#326]
It would be great to automatically create a Pull Request to add a basic `.zappr.yaml` file to the repository. 

[Creating](https://developer.github.com/v3/repos/contents/#create-a-file) a file and [opening a Pull Request](https://developer.github.com/v3/pulls/#create-a-pull-request) are both easy to do through the API. The added benefit of doing this is that **Zappr will already be in the list of recent status checks** when configuring Protected Branches.

**Comment by prayerslayer** [comment]
I propose we do such a PR when a check is enabled and all of the following is true:

* There is no other check enabled
* There is no Zapprfile in the repository

**Comment by AlexanderYastrebov** [comment]
Hello. 
In our repos https://github.bus.zalan.do/balance we ended up with common config:

```
X-Zalando-Team: balance
X-Zalando-Type: code
```

I am wondering is it possible for Zappr to have default value `X-Zalando-Type == code` and infer team name from github url so we can completely remove this config files?

**Comment by prayerslayer** [comment]
Hi @AlexanderYastrebov, as the `X-Zalando` prefix suggests these are custom extensions that Zappr doesn't know of, so there is no way to provide default values. Thanks for the suggestion though.
