### ISSUE TITLE
Add Standard Links

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#328]
We need to provide [standard links](https://developer.github.com/integrations-directory/getting-listed/#provide-standard-links) on the Zappr landing page and/or on main page.

- [x] Link to documentation (readthedocs)
- [x] Link to GitHub repository
- [x] Link to Terms of service
- [x] Link to support (e.g. Gitter)
- [x] Link to status
- [ ] Include EU cookie notice

**Comment by prayerslayer** [comment]
I set up a [twitter](twitter.com/zalando_zappr) for status until #357 is finished.
