### ISSUE TITLE
URL broken

### ISSUE THREAD

**Issue by femueller** [zalando/zappr#361]
The URL in file `client/containers/Login.jsx` should be `http://www.zalando.com/` instead of `https://zalando.com`, since `https://zalando.com` does not serve HTTPs.

**Comment by prayerslayer** [comment]
Good catch.

**Comment by femueller** [comment]
Close for reason:
"This could be either dropped or still be updated, depending how you want.
Since, I am in the responsible team to handle these URL redirects properly, we've fixed the issue.

Which means it does now work, but will be redirected."
