### ISSUE TITLE
Invalid check status for merged pull requests

### ISSUE THREAD

**Issue by olkulyk** [zalando/zappr#364]
After pull request is merged and closed, zappr check statuses are shown as "in progress" (was all-passed before the merge)

![screenshot](https://cloud.githubusercontent.com/assets/12675197/16804295/5d5d8c7c-490b-11e6-8911-87cc59733d32.png)

**Comment by prayerslayer** [comment]
Would you mind giving me an example where that happened? I've never seen this.

**Comment by prayerslayer** [comment]
I've added unit tests, Zappr doesn't call Github on `pull_request.closed` 😕❓❓❓ No idea what's happening.

**Comment by prayerslayer** [comment]
Hi, does this still happen to you?

**Comment by olkulyk** [comment]
Not sure what has changed but not anymore.
Will reopen if happens again. Thanks!

**Comment by prayerslayer** [comment]
I suspect it was somehow caused by the back-then overloaded GHE instance.
