### ISSUE TITLE
Consider supporting MAINTAINERS file for approvers

### ISSUE THREAD

**Issue by hjacobs** [zalando/zappr#375]
Would be nice to support reading the `MAINTAINERS` file (which we use anyway) the same way as LGTM does (https://lgtm.co/docs/overview/).

The default Zappr config should automatically allow approvals from MAINTAINERS.

**Comment by prayerslayer** [comment]
I guess one could do:

~~~ yaml
approvals:
  from:
    maintainers: true
~~~

To automatically add them to the list of valid approvers.

# PLOT TWIST

Currently our MAINTAINERS look like this:

    Tobias Sarnowski <tobias.sarnowski@zalando.de>

Neither does this contain the Github handle (`sarnowski`) nor the email used for the Github account.

Would you extend the MAINTAINERS file?

**Comment by hjacobs** [comment]
@prayerslayer maybe one of name or email needs to match the GitHub account (public info)?

**Comment by prayerslayer** [comment]
I'd prefer only one. What about:

    sarnowski <tobias.sarnowski@zalando.de>
    prayerslayer <nikolaus.piccolotto@zalando.de>

**Comment by hjacobs** [comment]
@prayerslayer let's not change the existing `MAINTAINERS` format just to make one tool happy. Having some cryptic GitHub username in `MAINTAINERS` binds the repo to the git hosting platform --- which is IMHO very bad.

**Comment by prayerslayer** [comment]
Sounds reasonable.

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
