### ISSUE TITLE
Private repo support?

### ISSUE THREAD

**Issue by bootstraponline** [zalando/zappr#391]
Does Zappr support private repos?

> PullApprove supports private repositories, whereas currently we do not. We will support them in the future, though.
https://zappr.readthedocs.io/en/latest/competitors/
>
> https://news.ycombinator.com/item?id=12035346

**Comment by hjacobs** [comment]
I guess @prayerslayer or @mfellner can answer this :smile:

**Comment by bootstraponline** [comment]
I found this response on gitter:

> @prayerslayer Jun 09 11:17
> Hi, currently only public repositories are supported as we ask for public_repo scope. However we would find it cool to give our users the choice between various levels of access.
> There is an issue already, but not much else zalando/zappr#90

If someone self hosts zappr, seems like private repos shouldn't be a problem?

**Comment by bootstraponline** [comment]
Is this change to `system.yaml` all we'd need to support private repos?

```diff
GITHUB_SCOPES:
  - user:email
- - public_repo
+ - repo
  - admin:repo_hook
```

**Comment by mfellner** [comment]
@bootstraponline That's right! We just didn't want to include this by default (see #90).

If you deploy your own Zappr instance you can even override all the config values with environment variables.

**Comment by bootstraponline** [comment]
Awesome! Are there plans to support that as an option on the public instance? You could even charge $$ for the private repos.

**Comment by mfellner** [comment]
We definitely want to make Zappr more useful to more people and private repos is pretty much a no-brainer. There are currently no plans to monetize Zappr however security is a major concern. 

1. We need to allow users to gradually give Zappr more permissions
2. There must be away to delete all user-data, access tokens etc. once a user stops using Zappr

Both of these things are already on our roadmap! 😄

**Comment by bootstraponline** [comment]
Nice. Thanks for the info.

**Comment by mfellner** [comment]
Closing in favor of #392.

**Comment by prayerslayer** [comment]
There are also minor code changes necessary, e.g. [here](https://github.com/zalando/zappr/blob/master/server/service/GithubService.js#L29).
