### ISSUE TITLE
Support Private Repositories

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#392]
Allow users to add the `repo` scope in order to use Zappr with private repositories. This scope gives full access to private repositories thus we must not add it by default.

#### Dependencies

-  #90 
- #329

**Comment by prayerslayer** [comment]
For Enterprise installations it would be already sufficient to just drop/change the `visibility` parameter from [here](https://github.com/zalando/zappr/blob/master/server/service/GithubService.js#L29)?

**Comment by j0k3r** [comment]
@prayerslayer it's all the case for non Entreprise install.

Switching the `GITHUB_SCOPES` isn't enough this line should also be switched to `all` instead of `public`.
Maybe this line can be switched to `all` for every one. Scope will limit private repo to show up.

**Comment by prayerslayer** [comment]
Yes, true, we also need to change the scopes. However in Enterprise installations you provide the configuration yourself anyways, including scopes to request. For Github.com we really need to do #90 first.

I'd expect `all` to work too.

**Comment by mfellner** [comment]
Closed with #406
