### ISSUE TITLE
Invalid HttpResponse for hooks.

### ISSUE THREAD

**Issue by jbellmann** [zalando/zappr#40]
Registered a repository for zappr and had a look into 'webhooks'-settings the hook was marked red.

<img width="901" alt="screen shot 2016-03-04 at 08 23 27" src="https://cloud.githubusercontent.com/assets/58709/13520726/1998c1da-e1e3-11e5-922b-71a279e10e1e.png">

Maybe this is a issue, maybe not.

**Comment by prayerslayer** [comment]
Yeah, at zappr.opensource.zalan.do there is "something" running, but we're not sure it works yet. (DB migrations apparently didn't work so good in production.)

But thanks for trying it out, we'll ping here once we're reasonably sure that we got something working.

**Comment by mfellner** [comment]
We are going to take care of this with #42

**Comment by prayerslayer** [comment]
Fixed by #42
