### ISSUE TITLE
Less negative emoji for approval veto

### ISSUE THREAD

**Issue by priesus** [zalando/zappr#400]
"👍"  fells like a good expression for approving someone else's work.
"👎 " doesn't feel so fit as indicator that something needs more work.

It's especially bad, because the defined pattern doesn't allow me to add a comment to the "👎 ".

I personally never use the PR veto in GHE just because of the negative emotional impact I feel it may have on my team mates.
Just imaging someone put's a 👎  on your PR without explanation.

Stash also had a different naming for PR feedback: "Approve" & "Needs work". There was no "veto" or "disapprove".

Proposal: Make ✋  (raised_hand) the default emoji to indicate that a PR needs work before being merged.

**Comment by prayerslayer** [comment]
> Just imaging someone put's a 👎 on your PR without explanation.

That's a problem of your team/organization, really.

I think we have different semantics of the veto in mind. This is not "needs work." This is "has a bug so serious it must never land in production." Thus it should also be used sparingly.

Maybe what you want to convey would be better done by just not approving? That's how our team does it.

**Comment by priesus** [comment]
True, we may also solve this by simply not approving. I thought it may be cool to make it transparent in the PR checks when someone thinks the current state shouldn't be merged.

I know 1 veto blocks the approval and I think this makes totally sense. If anyone feels like a PR shouldn't be merged in the current state, the team should discuss and agree on how to proceed (either work on the code some more or change the veto into an approval).

To me it feels better to say "We'll merge this after X has been changed in the PR" instead of saying "No, this isn't going to be merged".

**Comment by prayerslayer** [comment]
> I thought it may be cool to make it transparent in the PR checks when someone thinks the current state shouldn't be merged.

That's also the case now. When you don't approve, it's "pending". When you completely disagree, it's "failed". One could of course introduce a third option, but I'm not sure if it would provide a benefit. ("1 person approves and 2 are in slight discomfort"? :grin:)

> To me it feels better to say "We'll merge this after X has been changed in the PR" instead of saying "No, this isn't going to be merged".

Sure, but that's what comments are for. You can't express that meaningfully in an emoji anyways.

Also a (or even "the") reason why we chose thumbs-down as the veto emoji is symmetry. Agree = :+1: (+1), disagree = :-1: (-1). Easy to remember/infer.

> True, we may also solve this by simply not approving.

Closing this then. Thanks for discussing 👏
