### ISSUE TITLE
Change base of PR

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#410]
Github now supports [changing the base](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) of a pull request. As usual with new features, it's not yet reported via web hooks. For us it will probably be the same as `pull_request.synchronize`, ie we invalidate all approvals and vetoes that came before.

**Comment by prayerslayer** [comment]
Quick check revealed that this is now reported as a `pull_request.edited` event, which Zappr currently does not handle.

Required steps:

- [ ] Keep track of current base branch in database, as we don't want to reset approvals when the description is edited

- [ ] React on `pull_request.edited`: Check if base branch changed, if so reset approvals

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
