### ISSUE TITLE
Support Github Teams

### ISSUE THREAD

**Issue by danielgsims** [zalando/zappr#412]
Hello,

I was wondering if there was a plan to support Github Teams, or any specific reason why they've been left out so far?

Thanks!

**Comment by prayerslayer** [comment]
I haven't checked in a while, but the reason why we didn't support them from the start is that the organisations API just didn't fit well for our use case. I.e. you had to look up teams by numeric ID instead of `org/team` and you had to be an admin of the organisation to check team membership.

**Comment by danielgsims** [comment]
I just checked. This still seems to be the case. You have to be an authenticated user who is able to see the team. Thanks for the quick replay!

**Comment by prayerslayer** [comment]
You're welcome. Please reopen if you have further questions on this topic.

**Comment by smvilar** [comment]
Hi there, I was just checking the [comparison with PullApprove](
https://zappr.readthedocs.io/en/latest/competitors/) and it says "As of now, every customization available in PullApprove is also available in Zappr."
That's not true because of this issue. Any new plans about supporting teams?

**Comment by harti2006** [comment]
hi @smvilar, it looks like PullApprove has evolved a lot since the last comparison. Thanks for letting us know.
Regarding "team support": There was no plan to add it yet. But feel free to reopen the issue, so it can be evaluated and discussed again.

**Comment by gonpombo8** [comment]
any news on this ?

**Comment by rashamalek** [comment]
Hi @gonpombo8 Currently there is no plan to add it yet.
