### ISSUE TITLE
Specification is not validated after (only) description change

### ISSUE THREAD

**Issue by xjrk58** [zalando/zappr#413]
It seems that the specification validity is not checked if only pull request description changes (e.g. no description provided during the pull request creation), but only after pushing more commits to the related branch.

**Comment by prayerslayer** [comment]
Hi, can you give a little bit more context, e.g. whether or not you're using this with Github Enterprise?

**Comment by prayerslayer** [comment]
Solution: Upgrade GitHub Enterprise installation.
