### ISSUE TITLE
Impossible to fix "PR's body failed check 'contains-issue-number'"

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/zappr#414]
Zappr complains about:

`zappr/pr/specification — PR's body failed check 'contains-issue-number'`

If I update PR body, check is not retriggered

Also this check could be enhanced to check PR body  OR title

**Comment by prayerslayer** [comment]
Hi, this is a problem your GitHub Enterprise installation, please complain to the relevant authorities that they upgrade :wink:

**Comment by prayerslayer** [comment]
As a workaround: Close and reopen.

**Comment by innokenty** [comment]
Happens to me on a public GitHub as well: https://github.com/zalando-incubator/zally/pull/442
