### ISSUE TITLE
We got checks on a commit which is (obviously) not a PR

### ISSUE THREAD

**Issue by j0k3r** [zalando/zappr#422]
We are using Zappr (from https://zappr.opensource.zalan.do/) since few days now, it works great.
But I got a strange behavior few minutes ago.

I cherry-picked some commits into an other branch and then pushed them.
In the comment, I mentioned a PR from where commits were cherry-picked.

Browsing the commit history I noticed a pending check on the last commit. I was sure it was Travis but hovering the bubble showed both approval & pr/specification from Zappr.

You can see it here: https://github.com/wallabag/wallabag/commits/2.1 (last commit)

**Comment by prayerslayer** [comment]
Hi, that seems indeed weird. However the commit you mentioned is the last commit on this pull request (https://github.com/wallabag/wallabag/pull/1999), I guess that's where the status comes from. I can double-check tomorrow, but probably Github just keeps any statuses it received around, no matter on which branch they were on.

**Comment by j0k3r** [comment]
Hum could be that. Good point.

**Comment by j0k3r** [comment]
I've just pushed more commits to the same branch and it looks like status are coming from the PR you mentioned.
I'm closing the issue.
Thanks for the explanation :)

**Comment by prayerslayer** [comment]
You're welcome, glad you resolved it ☺️
