### ISSUE TITLE
Impossible to fix "PR's body failed check 'contains-issue-number'"

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/zappr#425]
Zappr complains about:

zappr/pr/specification — PR's body failed check 'contains-issue-number'

If I update PR body, check is not retriggered

I am reopening it (previous #414) since:

1. Suggestion `Hi, this is a problem of your GitHub Enterprise installation, please complain to the relevant authorities that they upgrade :wink:` is not describing WHY should I complain about Zappr to github relevant authorities and WHAT about exactly should I complain.
2. Feature request `Also this check could be enhanced to check PR body OR title` was not considered

PS: But thanks for `As a workaround: Close and reopen PR.` :)

**Comment by AlexanderYastrebov** [comment]
My point is that I am required to use Zappr AND I have to move forward and merge pull requests that is why this issue should be resolved clearly (also for others to avoid it)

**Comment by prayerslayer** [comment]
Hi, sorry for not explaining it thoroughly, it just comes up so often. I should add this to the FAQ page.

1. Github Enterprise is behind public Github feature-wise. Always. This specific problem you have is GHE not reporting `deleted`/`edited` events in the web hooks. That's also why close+reopen helps. So upgrading GHE will solve this problem eventually. It's not something that we (Zappr) can fix.
2. Yes, could be enhanced. No, will not happen in the near future as Zappr already works according to our compliance requirements.

Does this answer your questions?

**Comment by AlexanderYastrebov** [comment]
As I am using GHE from Zalando AND Zappr is developed by Zalando AND compliance requirements comes from Zalando could you communicate with Zalando to upgrade GHE then?

**Comment by prayerslayer** [comment]
Sure, but keep in mind you can only update what GitHub puts into the next Enterprise version :) Will close as this seems to be solved.
