### ISSUE TITLE
Change the default emoji for vetos

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/zappr#437]
Using :-1:  as a veto indicator is pretty harsh. I'd consider it to be more of a *needs work* (similar to Stash). So a down vote doesn't really capture it. What about using :collision: for this? Potentially allowing both?

**Comment by whiskeysierra** [comment]
Or :raised_hand:

**Comment by prayerslayer** [comment]
Hi, we had this discussion before: https://github.com/zalando/zappr/issues/400

Main reason why I'm not fond of this is that it's hard to infer, because you lose the symmetry of thumbs up/down.
