### ISSUE TITLE
Check for open tasks

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/zappr#440]
I'd like to see a **zappr** check on [open tasks](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) in the pull request description. As checking/un-checking a task item is notified as "edit comment" an integration might be possible.

**Comment by prayerslayer** [comment]
Hmm yes, that might work.

**Comment by tunix** [comment]
Hi All, I just wanted to let you know that I'm working on this. 😉

**Comment by tunix** [comment]
This issue is now fixed. :)

**Comment by prayerslayer** [comment]
Essentially yes :)
