### ISSUE TITLE
Check modified files against patterns

### ISSUE THREAD

**Issue by svoop** [zalando/zappr#447]
A fifth filter would be great which applies regular expressions to the content of all added or modified text files, primarily to prevent debuggers from hitting production. A default pattern for JS and Ruby could be:

    /^\s*(debugger|binding\.pry)/

**Comment by prayerslayer** [comment]
I don't follow. Why is this not handled by your `.gitignore`?

**Comment by svoop** [comment]
I don't see how this could be done with `.gitignore`.

Say, you have a JS source code file in a commit which is part of a PR. And that file contains a line with `debugger` (a forgotten breakpoint). I'd like to deny the PR in this case.

**Comment by prayerslayer** [comment]
Ahhh now I understand (thought this was a special type of file you're mentioning). Well, no. Then I think this would be better handled by a lint step in your build pipeline (say, with Travis), as there are already tools for exactly this purpose. See e.g. [no-debugger rule](http://eslint.org/docs/rules/no-debugger) of ESLint.

**Comment by svoop** [comment]
You're right of course, however, I'm not really inclined to go through all that hassle just to kick leftover debuggers.

**Comment by prayerslayer** [comment]
> I'm not really inclined to go through all that hassle just to kick leftover debuggers

Well, you don't necessarily have to. There are other services like [codacy](https://github.com/integrations/codacy) which are essentially linting-as-a-service.

Either use one of those or change your build pipeline. You will have better feature support anyways compared to us doing regex magic.
