### ISSUE TITLE
Toggles should be only enabled when user has admin access

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#454]
Currently anyone who has any kind of access to a repo can try to toggle checks. However it will only work for admins (due to the recently added branch protection #86), leading to a bad user experience.

Alternatively or even additionally we should improve the error messages. Generic 404 error message doesn't help much.

**Comment by LappleApple** [comment]
@prayerslayer @mfellner @spaudanjo Can we add a "Help Wanted" label here?

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
