### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by PetrGlad** [zalando/zappr#455]
I enabled "Approval Check" (and only this function so far) for my repository but now pull request shows not only "Approvals check" (which is expected) but also following
> Some checks haven’t completed yet
> 1 expected and 1 pending checks
> Required  zappr/pr/labels — Waiting for status to be reported 

1. On GitHub Enterprise I see no configuration options that would allow me to change tags
2. "Effective configuration" in Zappr does not seem to contain "tags" relevant config
3. When I try to enable "Tags" function (which is currently disabled) it says that

> Error during check processing
> Check pullrequestlabels already exists for repository 4793.

So now "tags" check prevents me from merging request and I have no Idea how to work around this except disabling Zappr for my repository.

**Comment by PetrGlad** [comment]
Just noticed that trying to toggle "tags check" actually adds this check to protected branch config (and then returns error, apparently).

**Comment by prayerslayer** [comment]
The labels check does have a bug in that it does not properly use the default config. Also there's a migration missing that adds the new enum value to the type. And the order of doing things is probably wrong.

Arguably not the best code I shipped. Will fix all of this.
