### ISSUE TITLE
LGTM will not require a licensing fee

### ISSUE THREAD

**Issue by bfeldkamp3** [zalando/zappr#471]
This is a docs issue. LGTM is open sourced under Apache 2.0 so they won't be requiring a licensing fee for enterprise github. See here: https://github.com/lgtmco/lgtm-docs/issues/7 

There should be an update to https://zappr.readthedocs.io/en/latest/competitors/ to remove the line 

> LGTM "will require a modest licensing fee for on-premise enterprise use in the near future". Zappr/Zappr Enterprise is completely free (as in beer and freedom) to use.

**Comment by prayerslayer** [comment]
Thanks for noticing, I just copied that from their FAQ page.

Also: What's up with all the pull requests? #468 #469 #470 :grin:

**Comment by bfeldkamp3** [comment]
lol I just didn't read the message on contributing at first! Sorry! Then I saw I was supposed to create an issue first...

**Comment by prayerslayer** [comment]
Any comment on my edits? Would you care updating the whole LGTM section (as you appear to care about it)?

**Comment by bfeldkamp3** [comment]
I actually don't know enough about LGTM unfortunately. I was just browsing around and saw your comparison page (which is most excellent) and thought I'd contribute back just to keep it accurate!

**Comment by prayerslayer** [comment]
Alright, thank you very much then! I'll fix this asap.
