### ISSUE TITLE
Take some ideas from homu

### ISSUE THREAD

**Issue by hgrecco** [zalando/zappr#477]
I have been using homu (http://homu.io) in another project and I think it has some features which are really useful. Basically it merges for you and you can queue multiple ones PRs to be merged (even with a priority). This is very useful, in particular for projects with long tests.

**Comment by LappleApple** [comment]
Thanks for the note, @hgrecco. Are you using Zappr or have any plans?

**Comment by hgrecco** [comment]
I am testing it in hgrecco/pint and I have also collaborated with projects using homu. 

What I like about homu is that you can mark a PR for merging and move to the next. Even though merging will be done later for you, it is still safe because testing is done just before merging. With zappr, after a merge, I (as opposed to the computer!) have to wait until the next PR is tested against the the new tip before merging.

What I like about zappr is that you have a much finer control about approvals.

**Comment by prayerslayer** [comment]
> With zappr, after a merge, I (as opposed to the computer!) have to wait until the next PR is tested against the the new tip before merging.

I guess one could add a config option and let Zappr do the merge when all status checks are done, but this would be quite some work (Zappr works push-based, this feature would need a polling execution model) and I'm not convinced that this effort would be justified.

I didn't find other features of homu, so I'll close this for now but feel free to continue the discussion.

**Comment by hgrecco** [comment]
Sorry to come with this again, but I am still looking for solutions and I really like zappr flexibility. One last question, why you say it has to be pull based? How about zappr keeps a queue of every PR that has been approved and the merges one after the other? It would still be push based, right?

**Comment by prayerslayer** [comment]
Hi there!

> why you say it has to be pull based

There is [no webhook](https://developer.github.com/webhooks/#events) in Github for commit status updates. Since Zappr would have to wait until all required status checks are reported and green, it has to poll the Github API.

> How about zappr keeps a queue of every PR that has been approved and the merges one after the other

See above, Zappr might not be the only service having an opinion about your pull request. Also, since actions on Github can be invoked in multiple ways we try to keep as few local state as possible. Implementing this with Webhooks would be the correct way in my opinion.

**Comment by hgrecco** [comment]
I do agree that webhooks would be the right way. thanks for your answer and thanks for zappr.
