### ISSUE TITLE
Auto-Assign Reviewers

### ISSUE THREAD

**Issue by jcranky** [zalando/zappr#481]
It would be cool if reviewers were automatically assigned from a predefined list. The number is reviewers could come from the mininum approvals setting. A "assignment" in this case could be simply a new comment in the issue, or an "official" github assignment.

**Comment by prayerslayer** [comment]
You're proposing a solution, could you explain to me what problem you're trying to solve? A static list doesn't sound that useful to me.

**Comment by jcranky** [comment]
So in our team we have 5 members, and we want two approvals. Currently we manual "randomly" decide who are our reviewers. My idea is that this choosing could be done automatically - and unbiased as well :)

**Comment by prayerslayer** [comment]
Oh okay, that randomization wasn't obvious to me from your first post. Have you checked if [facebook/mention-bot](https://github.com/facebook/mention-bot) would work for you? It doesn't randomize, but tries to be smart.

**Comment by jcranky** [comment]
I never heard of that one, will have a look, thanks. Just not sure If I can have it installed in our GHE - seems like a fit for OS projects though!

**Comment by alexkops** [comment]
But https://github.com/facebook/mention-bot#how-to-run-the-bot-on-github-enterprise

**Comment by prayerslayer** [comment]
Yeah, we could run mention-bot for our GHE if there is enough demand :)

**Comment by jcranky** [comment]
Cool, who I have to bother to get that, I'll follow up internally :)
