### ISSUE TITLE
ux issue in "effective configuration panel" when selecting text

### ISSUE THREAD

**Issue by aryszka** [zalando/zappr#489]
steps to reproduce:

1. select a project (with a valid config)
2. click on 'validate zappr configuration'
3. in the result panel click 'effective configuration'
4. select some configuration text in the opened panel

what happens at this point is that the panel gets closed

**Comment by prayerslayer** [comment]
Yes, that's a bit annoying...

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
