### ISSUE TITLE
Confusing error message for default configuration

### ISSUE THREAD

**Issue by PetrGlad** [zalando/zappr#490]
We have default configuration for the project with .zappr.yaml containing only
```yaml
X-Zalando-Team: "our-team"
```
The pull requests are rejected with message `PR's body failed check 'contains-issue-number'`
However I would expect only non empty body requirement in our case and any non empty PR description does make this check pass.

So error message in this case is misleading. It should likely be "PR description is required."

**Comment by prayerslayer** [comment]
Zappr tries different heuristics sequentially throws the last one failing at you, if none succeeds. So this behavior is expected.

> However I would expect only non empty body requirement in our case and any non empty PR description does make this check pass.

That's a wrong assumption. I'll update the docs to include the default config for this check, but just not empty doesn't cut it. Currently you need more than 8 characters.

Hope this helps.

**Comment by prayerslayer** [comment]
Also, you can use the "Validate Zappr configuration" button to view your effective configuration (user config merged with default config).

![image](https://cloud.githubusercontent.com/assets/878512/23364867/0d3ab1fc-fd01-11e6-890a-18ecb720fc1d.png)
