### ISSUE TITLE
False "approved" pull request

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [zalando/zappr#499]
Repository zappr config requires 2 approvers.

Two PRs createrd to merge branch F(eature) to branches R(elease) and M(aster).

PR F->R approved by two guys and was merged
PR F->M was approved only by one guy but it show as approved by two and can be merged.

See screenshots.

![screen shot 2017-03-09 at 17 00 45](https://cloud.githubusercontent.com/assets/283266/23759164/39118344-04ec-11e7-895e-7b971c4d1739.png)

![screen shot 2017-03-09 at 17 00 37](https://cloud.githubusercontent.com/assets/283266/23759155/3289f632-04ec-11e7-9dd4-ff5982fd17f1.png)

**Comment by prayerslayer** [comment]
See also #465. Since you approve a commit id and not a diff, this is expected behavior.
