### ISSUE TITLE
High CPU load for unknown reasons

### ISSUE THREAD

**Issue by sebastianpoeplau** [zalando/zappr#507]
Occasionally we see sudden load spikes, typically resulting in the instance being killed because it doesn't respond to the health check anymore. The CPU load will raise to 100% without obvious reasons; in particular, we don't see unusual patterns in the number of requests. We might be locked in some inefficient algorithm or some sort of blocking operation.

**Comment by sebastianpoeplau** [comment]
First attempt at an explanation: The algorithm for [filtering out modified comments](https://github.com/zalando/zappr/blob/master/server/checks/Approval.js#L311) is quadratic, so it might cause high load in some cases. However, the table of frozen comments (`zappr_data.frozen_comments`) is flushed after a PR is processed, so we can't reconstruct the state at the time of the incident. At present it only contains some 70 entries...

**Comment by aermakov-zalando** [comment]
Kinda fixed with #511.
