### ISSUE TITLE
Add a new RepositoryHandler Function to sync a single Repository with Github

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando/zappr#520]
Right now there is only an API endpoint so sync all the repos a Github user has access to. For our needs this call takes too long as the user has access to all repositories in our GHE instance. Therefore we need to have another API endpoint which enables Zappr to just sync a single repo with Github and it's DB.

This is the function which syncs all repos with Github:
https://github.com/zalando/zappr/blob/master/server/handler/RepositoryHandler.js#L142

I think it should be not that hard to add a similar one for a single repo sync.

**Comment by hjacobs** [comment]
This was done with #521
