### ISSUE TITLE
Cheat 4-eyes principle by editing a comment

### ISSUE THREAD

**Issue by harti2006** [zalando/zappr#522]
Usually zappr is supposed to detect comments that are edited by someone different from the original author (i.e. some arbitrary question is turned into ":+1:") and freeze them. In a certain case this does not work properly:

## Steps to Reproduce 
Prerequisite: Have the approval check enabled
1. Open a PR
1. Person A approves (status: 1/2 approvals ✅ )
1. New commit is added (status: 0/2 approvals ✅ )
1. Person B approves (status: 1/2 approvals ✅ )
1. Person B changes the comment of Person A to any other comment (status: 2/2 approvals 🚫 )

## Additional Observations
- the next update (commit / comment / change of a comment / ...) fixes the broken state: The edited comment does not count anymore

**Comment by grassator** [comment]
You can also delete comment from Person B, which results in the same scenario
