### ISSUE TITLE
Add a check to enforce signed commits

### ISSUE THREAD

**Issue by duergner** [zalando/zappr#523]
Similar to the commit message check it would be great to have a possible check to enforce all commits to have a valid GPG signature.

**Comment by hjacobs** [comment]
@duergner do you really want to have that? This would prevent "squash merges" and you would lock-out any contributor without proper GPG signing setup (not really OSS or InnerSource friendly).

**Comment by harti2006** [comment]
Additionally this would also fail on edits that have been done by using the GitHub UI.

**Comment by duergner** [comment]
I see benefits for code bases that are critical. Loosing the support for squash-merges is acceptable in this cases (IMHO) as you could do local squash / rebase and push the squashed branch.

Wouldn't see it as a default enabled check rather an option to enable.

**Comment by lotharschulz** [comment]
Another option would be to ask github enterprise support if that could become a github (enterprise) feature. With [enabling required reviews for pull requests](https://help.github.com/enterprise/2.11/user/articles/enabling-required-reviews-for-pull-requests/) we saw one step towards replacing zappr with github approval flows.
