### ISSUE TITLE
Bug: Zappr uses approvals in different pull request

### ISSUE THREAD

**Issue by ePaul** [zalando/zappr#529]
**Wrong behavior**
When there are two pull requests from the same branch to different target branches, approvals on one of the pull requests are also counted in the other pull request.

This can look like that:

![zappr-okay-without-approvals](https://user-images.githubusercontent.com/645859/35728437-e39bd5e4-080b-11e8-94a5-e7e6c00a00d0.png)

Zappr reports that fulm and pebermann have approved, but they actually did not comment on this PR at all (apart from the initial comment), and there were no approvals after the last commit on this PR.

On another PR with the same head, but different target branch, those two people actually commented with :+1:.

The same way, a veto in one PR affects the other one too.

**Analysis**
It looks like Zappr manages the status just for the commit, independently on which PR this is about.

**Comment by ePaul** [comment]
One more observation: As soon as on the second PR we also get one approval (but two are needed), the already existing two approvals on the first PR are ignored for that first one, too.

**Comment by ePaul** [comment]
It looks like this is not fixable in the current design, as Github's statuses are only for individual commits, not specific for a PR. I just sent a support/feature request to them proposing having statuses per PR (or per merge commit), the support person forwarded it to the API team.

* [About statuses](https://help.github.com/articles/about-statuses/)
* [Statuses API](https://developer.github.com/v3/repos/statuses/)

**Comment by lotharschulz** [comment]
as discussed, this is not fixable -> closed.
