### ISSUE TITLE
Consider a :+1: in a review approval in addition to a comment

### ISSUE THREAD

**Issue by ancelotpinto** [zalando/zappr#536]
Currently, only 👍 in a comment is consider. Adding support for this will enable the use of the github feature where we can review changes since the last approval or comment.

This is useful in a situation where we give an approval and the user updates the PR after.

**Comment by lotharschulz** [comment]
https://zappr.readthedocs.io/en/latest/setup/#zappr-features-and-their-configuration-options lists several configuration options including `pattern` : `^(:+1:|👍)$`

With that you can configure other patterns to express that you like the change.

Would that help?

Apart from that, zappr approvals become void once a new commit is pushed to the PR in question.

**Comment by ancelotpinto** [comment]
Thanks, this information is useful.

I was referring specifically to the native github review process where we can comment with an approval, but I realised that this is already being tracked in this issue:

Support native approvals
https://github.com/zalando/zappr/issues/442

Please close this as a duplicate ticket to #442
