### ISSUE TITLE
Expired certificate on https://zappr.opensource.zalan.do/

### ISSUE THREAD

**Issue by przemoc** [zalando/zappr#542]
Just letting you know that:

> zappr.opensource.zalan.do uses an invalid security certificate.
> 
> The certificate expired on Sunday, September 09, 2018, 1:59:59 AM. The current time is September 9, 2018, 11:48 AM.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by rashamalek** [comment]
@przemoc thanks for the heads up and sorry for not monitoring it beforehand, The SSL Certificate issue is now fixed. We'll try to prevent such these cases in the future.
