### ISSUE TITLE
docs seem to be outdated

### ISSUE THREAD

**Issue by drummerwolli** [zalando/zappr#545]
for the purpose of maybe getting familiar with zappr development, i tried to run the local dev env stuff, but it seems outdated:
1. `docker-compose up postgres-dev` just throws a `ERROR: No such service: postgres-dev` message
2. the docs mention `docker-machine` commands.
    - on linux, docker machine was never a thing, or?
    - on mac, docker uses a more native approach nowadays, so no docker-machine command should be needed anymore. its still installed but a `docker-machine ip` cmd execution just throws also the error message `Error getting IP address: machine does not exist` (although my usual docker dev env is properly running and setup.
3. the link to the Github credentials (client credentials for the OAuth App) link to the allowed OAuth Applications for the current user. imho it should rather link to https://github.com/settings/developers

docker version:
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by fokusferit** [comment]
Thanks @drummerwolli ! I'm also starting to understand zappr better so we are 2 😄. I will ping @rashamalek as he might have better insights regarding local development and deployment. But I will check this out too.

**Comment by fokusferit** [comment]
SO just to track this:

- [x] docker-compose commands not working -> should be updated via #547 
- [ ] replace docker-machine ip with a better (more common approach)
- [ ] agreed. for local testing it should point to the personal settings and not to application part.

**Comment by drummerwolli** [comment]
the docs still mention docker-machine all over the place ....

**Comment by fokusferit** [comment]
As we stepped in (@frometor and me) with a limited amount of knowledge regarding Docker and the ecosystem, I would welcome any feedback in how we can get rid of it, if we even need that thing etc.. 

Right now, just be remembered that the work was done over Hack Week, some free time. Feel free to create a PR fixing that setup.

**Comment by drummerwolli** [comment]
I'll add a PR later this week, should be small ...

**Comment by drummerwolli** [comment]
ok, it got bigger than i thought. started to work on this here: https://github.com/drummerwolli/zappr/tree/remove_docker_machine ... this will include some ideas as well to simplify the whole setup. i finally managed to understand what is going on. lets see when i will continue with this.
