### ISSUE TITLE
readthedocs header hides parts of documentation

### ISSUE THREAD

**Issue by lotharschulz** [zalando/zappr#548]
![screen shot 2018-11-26 at 13 29 18](https://user-images.githubusercontent.com/1148268/49014115-4bd21580-f17f-11e8-8e3a-c28a818af88a.png)

**Comment by frometor** [comment]
@lotharschulz please have a look. This might solve the issue. I am quite certain that when I looked at the UI of the zappr documentation some weeks ago it was using the readthedocs theme.

**Comment by lotharschulz** [comment]
Thanks @frometor for your contribution!
@fokusferit please check and approve https://github.com/zalando/zappr/pull/549 if possible, so we can merge and deploy.

**Comment by fokusferit** [comment]
Let's merge it and then hopefully it will be fixed. 
Btw.
@frometor next time if such a PR is some sort of UI related, I would appreciate some Screenshot 😄
