### ISSUE TITLE
Accept webhook url as a config parameter

### ISSUE THREAD

**Issue by startnow65** [zalando/zappr#561]
Currently, webhook urls are built by concatenating the value of `HOST_ADDR` config entry with `/api/hook`. Please see [here](https://github.com/zalando/zappr/blob/master/server/service/GithubService.js#L234) for details.

It would be nice to allow specifying the webhook url as a config entry (`HOOK_URL` for example).
This would be extremely useful for self hosted deployments where Zappr is not accessible on the internet, but all webhooks are accepted through a single entry point accessible from the internet and routed internally (to Zappr and other recipients) based on rules.

**Comment by lotharschulz** [comment]
Probably that would be a new key in https://github.com/zalando/zappr/blob/master/config/config.yaml.

**Comment by startnow65** [comment]
Exactly

**Comment by fokusferit** [comment]
So the setup is basically, there is a Proxy / LB / Server between Github and Zappr you want to add to Github and that one later makes sure that any data from Github gets forwarded to the internal Zappr Endpoint, e.g. using AWS ApiGateway for example. I will update my PR comments than.

**Comment by startnow65** [comment]
> So the setup is basically, there is a Proxy / LB / Server between Github and Zappr you want to add to Github and that one later makes sure that any data from Github gets forwarded to the internal Zappr Endpoint, e.g. using AWS ApiGateway for example. I will update my PR comments than.

Correct
