### ISSUE TITLE
Quiz about Authorization Callback URL

### ISSUE THREAD

**Issue by luhaixun** [zalando/zappr#578]
Hi team,

I want to set up my own Zappr server with GitHub entperprise however I can't use OAuth authentication because of the wrong Callback URL and got 500 error.

I use IP Address like _http://<ip_address>:>3000_, which is the same as the homepage URL, is there any guide to check which URI pattern should I use?

Appreciate your help!

**Comment by rashamalek** [comment]
Hi @luhaixun ,
The Authorization callback URL should include /auth/github

In your case it should be
http://<ip_address>:>3000/auth/github

**Comment by luhaixun** [comment]
@rashamalek  thanks for the help somehow it doesn't work with below mismatch internal error so I think it's still a wrong URL?

`
GET /login 304 51.640 ms - -
GET /auth/github 302 1.232 ms - 5
GET /auth/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fenterprise%2F2.16%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch 500 1.008 ms - 46
`

**Comment by luhaixun** [comment]
@rashamalek I figure it out now. Two items need to be changed for setup a private server:

1. Callback URL: http://<ip_address>:3000/auth/github/callback
2. setup SSL certification correctly.
3. I now disable callback url in the code for a mismatch turnaround
