### ISSUE TITLE
500 Error when trying to enable on an organization repo

### ISSUE THREAD

**Issue by jonathanpollack** [zalando/zappr#64]
I tried to enable `zappr` on [delivero/gitworkflowsamples](https://github.com/delivero/gitworkflowsamples), which then resulted in an internal server error. See attached screenshot.

![screen shot 2016-03-05 at 16 41 43](https://cloud.githubusercontent.com/assets/17195793/13549446/8ac7487c-e305-11e5-9f26-cae01cb35034.png)

**Comment by mfellner** [comment]
Looking at the logs there was definitely and issue enabling hooks:

```
Mar  5 15:40:52 ip-172-31-137-250 docker/42557c80b096[835]: Sat, 05 Mar 2016 15:40:52 GMT zappr:repo-handler:info 2016-03-05T15:40:52Z jonathanpollack: Reloaded from Github
Mar  5 15:41:32 ip-172-31-137-250 docker/42557c80b096[835]: Sat, 05 Mar 2016 15:41:32 GMT zappr:github:error 2016-03-05T15:41:32Z 404 GET /repos/jonathanpollack/director/hooks { message: 'Not Found',
Mar  5 15:41:32 ip-172-31-137-250 docker/42557c80b096[835]: Sat, 05 Mar 2016 15:41:32 GMT zappr:api:error 2016-03-05T15:41:32Z [Error: Not Found]
...
Mar  5 15:41:32 ip-172-31-137-250 docker/42557c80b096[835]: ::ffff:172.31.15.0 - PUT /api/repos/17866643/approval HTTP/1.1 500 21 - 542.272 ms
...
Mar  5 15:41:35 ip-172-31-137-250 docker/42557c80b096[835]: ::ffff:172.31.15.0 - PUT /api/repos/30529798/approval HTTP/1.1 500 21 - 330.292 ms
```

**Comment by prayerslayer** [comment]
Apparently because we're constructing the URL out of `$username/$repo`, so Zappr thinks `delivero/gitworkflowsamples` is `jonathanpollack/gitworkflowsamples`, which does not exist.

**Comment by jonathanpollack** [comment]
Right on!
