### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#78]
Create a complete documentation for the users of Zappr.

**Tasks**
- [ ] project summary in README.md

**Comment by prayerslayer** [comment]
Ideally we write some markdown and host it on GH Pages?

**Comment by mfellner** [comment]
Depends on the information we want to deliver. The essentials should definitely be part of the README, as it's the first point of contact for visitors to Github. Further user documentation might be better located directly together with the web service.

**Comment by prayerslayer** [comment]
I was thinking of an FAQ covering for instance

* why do we need the scopes we ask for
* how to configure zappr for your project
* troubleshooting

You're right, this better belongs in the application. I'd still want to write that as Markdown, compile on app startup and serve as static html. (As opposed to putting this into React.)

**Comment by prayerslayer** [comment]
Done!
