### ISSUE TITLE
Automatically protect master branch

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#86]
Use the [protected branches API](https://developer.github.com/changes/2015-11-11-protected-branches-api/) to automatically protect the master branch when approvals are enabled for a repository.

**Comment by prayerslayer** [comment]
What if someone wants to use Zappr only as a suggestion, but not as a
requirement? Would a button in Zappr "protect master" also be good?

On 11 March 2016 at 09:55, Maximilian Fellner <notifications@github.com>
wrote:

> Use the protected branches API
> <https://developer.github.com/changes/2015-11-11-protected-branches-api/>
> to automatically protect the master branch when approvals are enabled for a
> repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/zappr/issues/86>.
>



-- 

undefined = () => {}

     __
   .´ o)=-
  /.-.'
 //  |\
 ||  |'  Nikolaus Piccolotto
,:)_/_   engineer.js

**Comment by whiskeysierra** [comment]
> What if someone wants to use Zappr only as a suggestion, but not as a
> requirement? Would a button in Zappr "protect master" also be good?

I wouldn't invent something that Github already provides.

**Comment by prayerslayer** [comment]
@whiskeysierra Valid point :)

I just think doing this automatically might be unexpected (as Travis doesn't do it either) and people tend not to read textual notes.

**Comment by mfellner** [comment]
There were recently some changes to the Protected Branches API announced: https://developer.github.com/changes/2016-06-27-protected-branches-api-update

**Comment by prayerslayer** [comment]
I changed my mind. We should just make every check a required status check automatically, because it makes sense for most of them anyways.
