### ISSUE TITLE
Support for Reactions

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#87]
Github just announced support for [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

![d55b8b7e-e6ba-11e5-9b31-59a8db92e456](https://cloud.githubusercontent.com/assets/1183636/13699868/8b82643c-e77d-11e5-9833-51a9756c8460.gif)

I did not see any API support yet, but that could be a great interface for approvals.

**Comment by prayerslayer** [comment]
Ya, they are apparently not in the API yet, I checked.

**Comment by prayerslayer** [comment]
Closing because comments are superior for our purposes.
