### ISSUE TITLE
Figure out why I cannot enable zappr for mfellner/hello-world

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#89]
Has this something to do with being a collaborator?

**Comment by prayerslayer** [comment]
Looks like when the project is a fork `GET ${project}/hooks` returns 404.

**Comment by prayerslayer** [comment]
Nope, works fine when I fork zappr or docker.

**Comment by mfellner** [comment]
Only administrators can enable githooks for repositories. Maybe we can find a way to better communicate this to the user.
